- name: Install latest version of Ansible on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - software-properties-common
          - python3-pip

    - name: Add Ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible

    - name: Install latest version of Ansible
      pip:
        name: ansible
        state: latest
        executable: pip3
