---
- name: Install Jenkins on Ubuntu Server
  hosts: all
  become: yes

  tasks:
  - name: Install python3-pip package
    apt:
      name: python3-pip
      state: present

  - name: Install AWS CLI
    pip:
      name: awscli
      state: present
