---
- name: Install Terraform on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'

    - name: Verify Terraform installation
      shell: terraform version
